// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjnboithphtxmtaukzuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqbmJvaXRocGh0eG10YXVrenV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzIzOTQsImV4cCI6MjA3MDkwODM5NH0.UwxIawlz1fvmQnW83mj29ymykeWiEoSTQPjyAmPW5ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});